# Generated by Django 6.0 on 2026-01-21 20:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('company_description', models.TextField()),
                ('office_address', models.TextField()),
                ('contact_email', models.EmailField(max_length=200)),
                ('contact_phone', models.CharField(max_length=15)),
                ('google_map_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='About_Trainers',
            fields=[
                ('trainer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trainer_title', models.CharField(max_length=200)),
                ('trainer_name', models.CharField(max_length=200)),
                ('trainer_image', models.ImageField(upload_to='trainer_images/')),
                ('trainer_bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses_Model',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_logo', models.ImageField(upload_to='course_logos/')),
                ('course_duration', models.CharField(max_length=50)),
                ('course_fee', models.IntegerField()),
                ('course_description', models.TextField()),
                ('course_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipOffers',
            fields=[
                ('internship_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internship_name', models.CharField(max_length=100)),
                ('internship_description', models.TextField()),
                ('technologies', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Notifications',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('company_posted_date', models.DateField(blank=True, default=None, null=True)),
                ('posted_date', models.DateField(blank=True, default=None, null=True)),
                ('job_description', models.TextField()),
                ('requirements', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NewBatchs',
            fields=[
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('timing', models.TimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=20)),
                ('quafication_requirements', models.CharField(max_length=100)),
                ('course_duration', models.CharField(max_length=50)),
                ('batch_type', models.CharField(choices=[('Weekdays', 'Weekdays'), ('Weekends', 'Weekends')], default='Weekdays', max_length=20)),
                ('status', models.CharField(choices=[('started', 'started'), ('upcoming', 'upcoming'), ('completed', 'completed')], default='upcoming', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_courses', to='VJISS_APP.courses_model')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_name', to='VJISS_APP.about_trainers')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus_Model',
            fields=[
                ('syllabus_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_courses', to='VJISS_APP.courses_model')),
            ],
        ),
        migrations.CreateModel(
            name='Create_User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[6-9][0-9]{9}$', 'Enter a valid 10-digit phone number.')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=6)),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='vjiss_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='vjiss_users', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student_Enrollment',
            fields=[
                ('enrollment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Interested', 'Interested'), ('NotInterested', 'NotInterested'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='VJISS_APP.courses_model')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apply_Internship',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('education', models.CharField(choices=[('Diploma', 'Diploma'), ('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('PhD', 'PhD')], max_length=200)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('internship_offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_offers', to='VJISS_APP.internshipoffers')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_applicants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
