# Generated by Django 6.0 on 2026-01-23 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VJISS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_enrollment',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_enrollment',
            name='status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Dropped', 'Dropped'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Batch_Enrollment',
            fields=[
                ('batch_enrollment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Pending', 'Pending'), ('Dropped', 'Dropped')], default='Pending', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_batches', to='VJISS_APP.newbatchs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_enrolled_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
